sudo: required
services:
  - docker

before_install:
  - docker build -t amr/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true amr/react-test npm test

language: generic

after_success: -docker build -t amr/multi-client ./client
  -docker build -t amr/multi-nginx ./nginx
  -docker build -t amr/multi-server ./server
  -docker build -t amr/multi-worker ./worker
